# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: image_powderaverage
description: Calculate the powder average of a 4D diffusion volume.
keywords:
  - DWI
  - Powder Average
  - BET
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - dwi:
        type: file
        description: Nifti DWI volume to compute the powder average on.
        pattern: "*.nii.gz"
        ontologies:
          - edam: http://edamontology.org/format_3989 # GZIP format
    - bval:
        type: file
        description: b-values file.
        pattern: "*.bval"
        ontologies: []
    - mask:
        type: file
        description: Binary mask to apply on the DWI volume.
        pattern: "*.nii.gz"
        ontologies:
          - edam: http://edamontology.org/format_3989 # GZIP format
output:
  pwd_avg:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*pwd_avg.nii.gz":
          type: file
          description: Powder averaged DWI volume.
          pattern: "*pwd_avg.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@gagnonanthony"
maintainers:
  - "@gagnonanthony"
